### ISSUE TITLE
wikipedia data load fails

### ISSUE THREAD

**Issue by davecramer** [CrunchyData/crunchy-demo-data#1]
\copy wikipedia (county, state, json_content, response_attr) from './wikipedia_copy.txt' WITH CSV QUOTE '^'
ERROR:  extra data after last expected column
CONTEXT:  COPY wikipedia, line 549: "^Gwinnett County^,^ Georgia^,^{"batchcomplete": true, "warnings": {"main": {"warnings": "Subscribe t..."

**Comment by thesteve0** [comment]
Works for me in the container. Let's try to figure out where it is going wrong for you

workshop=> \copy wikipedia (county, state, json_content, response_attr) from '/data/crunchy_demo_data/wikipedia/wikipedia_copy.txt' WITH CSV QUOTE '^';
COPY 3221

**Comment by davecramer** [comment]
Seems to work fine now, not sure what the problem was
